export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_PAGINATION = "GET_PAGINATION";
export const FILTER_BY_REGION = "FILTER_BY_REGION";
export const SORT_COUNTRIES = "SORT_COUNTRIES";
export const SEARCH = "SEARCH";
export const GET_DETAIL = "GET_DETAIL";
